# Generated by Django 2.1.5 on 2020-05-13 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PenaltyManager', '0003_penalty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 18, 38, 54, 698090)),
        ),
    ]
