# Generated by Django 2.1.5 on 2020-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
